version: '3'

services:
  bereal:
    container_name: bereal
    build:
      context: .
      dockerfile: bin.dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://admin:C3YGgFB7ul2NSfX@bereal-db/bereal
    logging:
      driver: "json-file"
      options:
        max-size: "60m"
        max-file: "10"
    restart: on-failure
    networks:
      - bereal

  db:
    container_name: bereal-db
    build:
      context: .
      dockerfile: db.dockerfile
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bereal
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: C3YGgFB7ul2NSfX
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - bereal

networks:
  bereal:
    name: bereal
